version: '3'
services:
  db:
    image: mariadb:10.5.9
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: kebab
      MYSQL_DATABASE: iwa
    networks:
      - backend
    volumes:
      - ./db_data:/var/lib/mysql
    restart: unless-stopped
    
  backend:
    build: ./src/IWA_Backend
    ports: 
      - 5000:80
    environment:
      IWA_CorsAllowUrls: http://localhost:8100,http://127.0.0.1:8100
      IWA_SeedInitialData: "true"
      IWA_MYSQL_HOST: db
      IWA_MYSQL_PORT: 3306
      IWA_MYSQL_DB: iwa
      IWA_MYSQL_USER: root
      IWA_MYSQL_PASS: kebab
    networks:
      - backend
    restart: unless-stopped
    volumes:
      - ./avatars:/app/AvatarData
    depends_on:
      - db
      
  frontend:
    build: ./src/frontend
    ports: 
      - 8100:80
    environment: 
      API_URL: http://127.0.0.1:5000
    restart: unless-stopped
    depends_on:
      - backend

networks:
  backend:
