version: '3'
services:
  db:
    image: mariadb:10.5.9
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: kebab
      MYSQL_DATABASE: iwa
    volumes:
      - ./db_data:/var/lib/mysql
    restart: unless-stopped
