name: Build and Test

on:
  push:
    # branches: [ master, develop ]
  pull_request:
    # branches: [ master, develop ]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore ./src/IWA_Backend/
      
    - name: Build
      run: dotnet build --no-restore ./src/IWA_Backend/
      
    - name: Test
      run: dotnet test --no-build --verbosity normal ./src/IWA_Backend/
  