name: Build and Test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/IWA_Backend/
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./src/IWA_Backend/
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./src/IWA_Backend/
  
  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Cache npm global modules (yarn)
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-  
          
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install yarn
        run: npm install -g yarn  
          
      - name: Install dependencies
        run: yarn install
        working-directory: ./src/frontend

      - name: Build frontend
        run: yarn build
        working-directory: ./src/frontend
        env:
          CI: false
      
      # TODO: Add unit testing when it is ready
      # - run: yarn test
      #   working-directory: ./src/frontend
      #   env:
      #     CI: false
